title: Monie Salon
email: africansisterbraidingsalon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Monie African Salon located in Salt Lake City, Utah. Specializes in African
  hairstyles and treatments.
baseurl:
url:
github_username: courtlandw97

# Build settings
baseurl: /court


gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
